name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite iniciar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do Repositório Atual (Onde o Action está configurado)
      - name: Check out this repository
        uses: actions/checkout@v2

      # Clonar o Repositório de Origem
      - name: Clone another repository
        run: |
          git clone https://github.com/henrique-toja/Projetosuperslim.git
          cd Projetosuperslim

      # Configurar Java JDK e Android SDK (Necessário para Build de APK)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # Distribuição do OpenJDK
          java-version: '11'

      - name: Download Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3
          cmake-version: 3.10.2

      # Construir o Projeto Android (APK)
      - name: Build APK
        run: |
          cd Projetosuperslim/app
          ./gradlew assembleDebug

      # Upload do APK como Artifact no GitHub Actions
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: Projetosuperslim/app/build/outputs/apk/debug/*.apk
